title: Francisco Marques Rodrigues
timezone: UTC
collections:
email: your-email@fmrsa.com
description: FMRSA website
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username: jekyll
plugins:
  - jekyll-postcss
  - jekyll-leaflet
sass:
  sourcemap: never
postcss:
  cache: false
exclude:
  - .gitignore
  - bin
  - node_modules
  - package-lock.json
  - postcss.config.js
  - README.md
keep_files:
  - assets/css/tailwind.css
  - assets/css/tailwind.css.map
