---
url: "psnev89.github.io"
baseurl: ""
title: Francisco Marques Rodrigues
timezone: UTC
email: your-email@fmrsa.com
description: FMRSA website
twitter_username: jekyllrb
github_username: jekyll
sass:
  sourcemap: never
postcss:
  cache: false
exclude:
  - ".gitignore"
  - bin
  - node_modules
  - package-lock.json
  - postcss.config.js
  - README.md
keep_files:
  - assets/css/tailwind.css
  - assets/css/tailwind.css.map
